import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ServiceManageUserService {
  constructor() {}

  avaColoe(letter: string) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    const colors = [
      '#FF5733',
      '#FFBD33',
      '#FFD133',
      '#FFE033',
      '#F1FF33',
      '#C1FF33',
      '#91FF33',
      '#61FF33',
      '#33FF36',
      '#33FF66',
      '#33FF96',
      '#33FFC6',
      '#33FFF6',
      '#33D9FF',
      '#33A9FF',
      '#3379FF',
      '#3349FF',
      '#6B33FF',
      '#9B33FF',
      '#CB33FF',
      '#FA33FF',
      '#FF33E6',
      '#FF33B6',
      '#FF339F',
      '#FF3376',
    ];

    const index = alphabet.indexOf(letter.toUpperCase());
    if (index !== -1) {
      return colors[index % colors.length];
    }

    return '#CCCCCC'; // Default color if letter is not found
  }

  // search clients
  CustomerProfile = [
    { title: 'All - picks up on every news item', value: 1 },
    { title: 'Charity - non VAT, assets, employees, UK', value: 2 },
    { title: 'Charity - VAT, assets, employees, UK', value: 3 },
    { title: 'General - VAT, employees, family owned', value: 4 },
    { title: 'H&W partnership - family, VAT, UK', value: 5 },
    {
      title: 'Limited Company + Private client - VAT reg, employees',
      value: 6,
    },
    { title: 'LTD - non VAT, employees, UK', value: 7 },
    { title: 'LTD - VAT, employees, international ops', value: 8 },
    { title: 'LTD - VAT, employees, UK', value: 9 },
    { title: 'Non dom client - family, non VAT', value: 10 },
    { title: 'Non dom client - family, non VAT', value: 11 },
    { title: 'Personal serv. co. - IR35, non VAT, no assets', value: 12 },
    { title: 'Personal serv. co. - IR35, VAT, no assets, UK', value: 13 },
    { title: 'Private client - family, non VAT, UK', value: 14 },
    { title: 'Self employed - family, VAT, no employees, UK', value: 15 },
    { title: 'Self employed - single, VAT, no employees, UK', value: 16 },
    { title: 'Self employed / Sole Trader, not VAT registered', value: 17 },
  ];

  searchClientsoptions = [
    { value: 'ClientID', title: 'Client ID' },
    { value: 'FirstName', title: 'First Name' },
    { value: 'SurName', title: 'Sur Name' },
    { value: 'Company', title: 'Company' },
    { value: 'EmailAddress', title: 'Email Address' },
    { value: 'CustomerProfile', title: 'Customer Profile' },
    { value: 'AccountManager', title: 'Account Manager' },
    { value: 'Verified', title: 'Verified' },
    { value: 'SICCode', title: 'SIC Code' },
    { value: 'Address', title: 'Address' },
    { value: 'DateAdded', title: 'Date Added' },
    { value: 'LastUpdated', title: 'Last Updated' },
    { value: 'TagsAssigned', title: 'Tags Assigned' },
  ];

  tagsAssignedlistItems = ['a1', 'aa1', 'aaa1', 'aaa1'];

  SEARCHCLIENT_DATA = [
    {
      clientId: 1,
      surname: 'Doe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'All - picks up on every news item',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 2,
      surname: 'Cmith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'Charity - non VAT, assets, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 3,
      surname: 'Zoe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'no',
      customerProfile: 'Charity - non VAT, assets, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'female',
      selected: false,
    },
    {
      clientId: 4,
      surname: 'Nit',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '10/12/2023',
      tags: 'aa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'female',
      selected: false,
    },
    {
      clientId: 5,
      surname: 'Michal',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '10/12/2023',
      tags: 'aa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 6,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'no',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '09/12/2023',
      tags: 'aa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 7,
      surname: 'Doe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '09/12/2023',
      tags: 'aa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'female',
      selected: false,
    },
    {
      clientId: 8,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '09/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 9,
      surname: 'Voe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'no',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '09/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 10,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'no',
      customerProfile: 'Charity - non VAT, assets, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 11,
      surname: 'Ioe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'female',
      selected: false,
    },
    {
      clientId: 12,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: '',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: '',
      selected: false,
    },
    {
      clientId: 13,
      surname: 'Doe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: '',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: '',
      selected: false,
    },
    {
      clientId: 14,
      surname: 'Cmith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: '',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: '',
      selected: false,
    },
    {
      clientId: 15,
      surname: 'Michal',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: '',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: '',
      selected: false,
    },
    {
      clientId: 16,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'Charity - non VAT, assets, employees, UK',
      accountManager: '',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 17,
      surname: 'Doe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: '',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 18,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: '',
      selected: false,
    },
    {
      clientId: 19,
      surname: 'Voe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: '',
      selected: false,
    },
    {
      clientId: 20,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 21,
      surname: 'Ioe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      customerProfile: 'LTD - VAT, employees, UK',
      accountManager: 'account Manager',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },
    {
      clientId: 22,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      customerProfile: 'Charity - non VAT, assets, employees, UK',
      accountManager: '',
      sICcode: '1',
      address: 'abc, xyz',
      date: '11/12/2023',
      tags: 'aaa1',
      registered: true,
      printedNewsletter: true,
      emailNewsletter: true,
      gender: 'male',
      selected: false,
    },

    // Add more client data as needed
  ];

  AccountManager = [{ title: 'Account Manager', value: 'AccountManager' }];

  Verified = [
    { title: 'Yes', value: 'Yes' },
    { title: 'No', value: 'No' },
  ];

  // search employyes
  EMPLOYEE_DATA = [
    {
      employeeId: 1,
      surname: 'Doe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 2,
      surname: 'Cmith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 3,
      surname: 'Zoe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 4,
      surname: 'Nit',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 5,
      surname: 'Michal',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 6,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 7,
      surname: 'Doe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 8,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 9,
      surname: 'Voe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 10,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 11,
      surname: 'Ioe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 12,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 13,
      surname: 'Doe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',
      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 14,
      surname: 'Cmith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 15,
      surname: 'Michal',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 16,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 17,
      surname: 'Doe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 18,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 19,
      surname: 'Voe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 20,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 21,
      surname: 'Ioe',
      firstName: 'John',
      companyName: 'ABC Inc.',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      employeeId: 22,
      surname: 'Smith',
      firstName: 'Jane',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      employeeProfile: 'All - picks up on every news item',

      qualification: 'normal',
      date: '10/12/2023',
      tags: 'a1',
      registered: true,
      gender: 'male',
      selected: false,
    },

    // Add more client data as needed
  ];

  searchEmployeessoptions = [
    { value: 'EmployeeID', title: 'Employee ID' },
    { value: 'FirstName', title: 'First Name' },
    { value: 'SurName', title: 'Sur Name' },
    { value: 'Company', title: 'Company' },
    { value: 'EmailAddress', title: 'Email Address' },
    { value: 'EmployeeProfile', title: 'Employee Profile' },
    { value: 'Qualification', title: 'Qualification' },
    { value: 'DateAdded', title: 'Date Added' },
    { value: 'LastUpdated', title: 'Last Updated' },
    { value: 'TagsAssigned', title: 'Tags Assigned' },
  ];

  EmployeeProfile = [
    { title: 'All', value: 1 },
    { title: 'Non-tax staff', value: 2 },
    { title: 'Partner/manager - corporate tax', value: 3 },
    { title: 'Partner/manager - general', value: 4 },
    { title: 'Partner/manager - personal tax', value: 5 },
    { title: 'Partner/manager - tax all', value: 6 },
    { title: 'Payroll administrator', value: 7 },
    { title: 'Tax staff - all', value: 8 },
    { title: 'Tax staff - corporate tax', value: 9 },
    { title: 'Tax staff - personal tax', value: 10 },
    { title: 'Tax staff - small business tax', value: 11 },
    { title: 'Vax staff - small business tax', value: 12 },
  ];

  Qualification = [
    { title: 'Important', value: 'Important' },
    { title: 'Normal', value: 'Normal' },
  ];

  // data import
  DATA_IMPORT_USER_DATA = [
    {
      userId: 1,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '2',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'pending',
      selected: false,
    },
    {
      userId: 2,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'yes',
      rows: '3',
      mode: '',
      from: 'CSV',
      status: 'pending',
      selected: false,
    },
    {
      userId: 3,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '0',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'pending',
      selected: false,
    },
    {
      userId: 4,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '1',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 5,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '5',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 6,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '1',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 7,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '1',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'analyse data',
      selected: false,
    },
    {
      userId: 8,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '8',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'analyse data',
      selected: false,
    },
    {
      userId: 9,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '1',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'pending',
      selected: false,
    },
    {
      userId: 10,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '4',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 11,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '8',
      mode: '',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 12,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '1',
      mode: '',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 13,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '6',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'analyse data',
      selected: false,
    },
    {
      userId: 14,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '1',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'pending',
      selected: false,
    },
    {
      userId: 15,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '4',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 16,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '1',
      mode: '',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 17,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '9',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },
    {
      userId: 18,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '7',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'analyse data',
      selected: false,
    },
    {
      userId: 19,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '1',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'analyse data',
      selected: false,
    },
    {
      userId: 20,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '7',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'pending',
      selected: false,
    },
    {
      userId: 21,
      dateAdded: '2/11/2023',
      type: '',
      share: 'no',
      rows: '1',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'pending',
      selected: false,
    },
    {
      userId: 22,
      dateAdded: '2/11/2023',
      type: 'client',
      share: 'no',
      rows: '1',
      mode: 'Add new Data Only',
      from: 'CSV',
      status: 'completed',
      selected: false,
    },

    // Add more client data as needed
  ];

  dataImportoptions = [
    { value: 'UserID', title: 'User ID' },
    { value: 'Type', title: 'Type' },
    { value: 'Share', title: 'Share' },
    { value: 'Rows', title: 'Rows' },
    { value: 'Mode', title: 'Mode' },
    { value: 'Source', title: 'Source' },
    { value: 'Status', title: 'Status' },
  ];

  dataImportshareoptions = ['yes', 'no'];

  dataImportStatusoptions = [
    { value: 'Pending', title: 'Pending' },
    { value: 'Completed', title: 'Completed' },
    { value: 'AnalyseData', title: 'Analyse Data' },
  ];

  // unsubcriber user
  UNSUBSCRIBER_USER_USER_DATA = [
    {
      userId: 1,
      name: 'Doe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 2,
      name: 'Cmith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 3,
      name: 'Zoe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 4,
      name: 'Nit',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 5,
      name: 'Michal',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 6,
      name: 'Smith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 7,
      name: 'Doe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 8,
      name: 'Smith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 9,
      name: 'Voe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 10,
      name: 'Smith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 11,
      name: 'Ioe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 12,
      name: 'Smith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 13,
      name: 'Doe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 14,
      name: 'Cmith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 15,
      name: 'Michal',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 16,
      name: 'Smith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 17,
      name: 'Doe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 18,
      name: 'Smith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 19,
      name: 'Voe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 20,
      name: 'Smith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 21,
      name: 'Ioe',
      dateAdded: '2/11/2023',
      emailAddress: 'john.doe@abc.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },
    {
      userId: 22,
      name: 'Smith',
      dateAdded: '2/11/2023',
      companyName: 'XYZ Corp.',
      emailAddress: 'jane.smith@xyz.com',
      verfied: 'yes',
      registered: true,
      gender: 'male',
      selected: false,
    },

    // Add more client data as needed
  ];

  searchUnsubcriberUseroptions = [
    { value: 'UserID', title: 'User ID' },
    { value: 'Name', title: 'Name' },
    { value: 'EmailAddress', title: 'Email Address' },
    { value: 'DateAdded', title: 'Date Added' },
  ];
}
