import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ManageContentService {
  // manage article
  CLIENT_DATA = [
    {
      clientId: 1,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be ',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'own',
      selected: false,
    },
    {
      clientId: 2,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 3,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'own',
      selected: false,
    },
    {
      clientId: 4,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'own',
      selected: false,
    },
    {
      clientId: 5,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 6,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'own',
      selected: false,
    },
    {
      clientId: 7,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 8,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 9,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'own',
      selected: false,
    },
    {
      clientId: 10,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 11,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'own',
      selected: false,
    },
    {
      clientId: 12,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 13,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 14,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'own',
      selected: false,
    },
    {
      clientId: 15,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'own',
      selected: false,
    },
    // Add more client data as needed
  ];

  // search article
  SEARCH_ARTICLE_CLIENT_DATA = [
    {
      clientId: 1,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be ',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'own',
      selected: false,
    },
    {
      clientId: 2,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 3,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'own',
      selected: false,
    },
    {
      clientId: 4,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'own',
      selected: false,
    },
    {
      clientId: 5,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 6,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'own',
      selected: false,
    },
    {
      clientId: 7,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 8,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 9,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'own',
      selected: false,
    },
    {
      clientId: 10,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 11,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'own',
      selected: false,
    },
    {
      clientId: 12,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 13,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'modified',
      selected: false,
    },
    {
      clientId: 14,
      imgUrl: '',
      arcticles: 'Here’s a simple example of a marketing',
      published_date: '06/11/2023',
      newsfeed: 'no',
      type: 'own',
      selected: false,
    },
    {
      clientId: 15,
      imgUrl: '',
      arcticles: 'very utility class in Tailwind can be',
      published_date: '06/11/2023',
      newsfeed: 'yes',
      type: 'own',
      selected: false,
    },
    // Add more client data as needed
  ];

  //select concept
  USER_DATA = [
    {
      id: 1,
      description: 'test',
      conceptDate: '29/11/2023',
      sendConceptDate: '29/11/2023',
      conceptType: 'Monthly Newsletter',
      selected: false,
    },
    {
      id: 2,
      description: 'test',
      conceptDate: '29/11/2023',
      sendConceptDate: '29/11/2023',
      conceptType: 'Monthly Newsletter',
      selected: false,
    },
    // Add more client data as needed
  ];

  constructor() {}
}
