import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ConnectionService {
  CONNECTION_DATA = [
    {
      connectionId: 1,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Doe',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 2,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Smith',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 3,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Johnson',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 4,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Brown',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 5,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Taylor',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 6,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Williams',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 7,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Lee',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 8,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Anderson',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 9,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Harris',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 10,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Clark',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 11,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Martin',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 12,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Young',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 13,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Garcia',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 14,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Rodriguez',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
    {
      connectionId: 15,
      exclude: '?????',
      imgUrl: '',
      fullname: 'Jackson',
      title: 'Long title Goes',
      published_date: '22/12/2022',
      platform: 'Facebook',
      selected: false,
    },
  ];
  constructor() { }
}
